name: rpc-account

dep:
  ops:
    type: git
    url: "https://github.com/hatlonely/ops.git"
    version: master

env:
  default:
    NAME: "rpc-tool"
    IMAGE_REPOSITORY: "rpc-tool"
    IMAGE_TAG: "$(git describe --tags | awk '{print(substr($0,2,length($0)))}')"
  dev:
    K8S_CONTEXT: "home-k8s"
    NAMESPACE: "dev"
    PULL_SECRET_NAME: "hatlonely-pull-secret"
    REPLICA_COUNT: 2
    INGRESS_HOST: "k8s.rpc.tool.hatlonely.com"
    SECRET_NAME: "rpc-tool-tls"
    REGISTRY_ENDPOINT: "{{.registry.aliyun.endpoint}}"
    REGISTRY_USERNAME: "{{.registry.aliyun.username}}"
    REGISTRY_PASSWORD: "{{.registry.aliyun.password}}"
    REGISTRY_NAMESPACE: "{{.registry.aliyun.namespace}}"
    ELASTICSEARCH_ENDPOINT: "https://security-master:9200"
    ELASTICSEARCH_PASSWORD: "{{.elasticsearch.password}}"
    JAEGER_SAMPLING_SERVER_URL: "http://jaeger-agent.monitoring:5778/sampling"
    JAEGER_REPORTER_LOCAL_AGENT_HOST_PORT: "jaeger-agent.monitoring:6831"

task:
  codegen:
    step:
      - docker login --username="${REGISTRY_USERNAME}" --password="${REGISTRY_PASSWORD}" "${REGISTRY_ENDPOINT}"
      - make codegen
  image:
    step:
      - make image
      - docker login --username="${REGISTRY_USERNAME}" --password="${REGISTRY_PASSWORD}" "${REGISTRY_ENDPOINT}"
      - docker push "${REGISTRY_ENDPOINT}/${REGISTRY_NAMESPACE}/${IMAGE_REPOSITORY}:${IMAGE_TAG}"
  config:
    args:
      cmd:
        type: string
        default: diff
        validation: x in ["diff", "get", "put"]
    step:
      - sh ${DEP}/ops/tool/render.sh ops/config ${TMP}/config
      - |
        cd ${TMP}/config && touch app_local.json;
        case "${cmd}" in
          "diff"|"") cfg --camelName --inBaseFile base_local.json -a diff --outBaseFile base.json;;
          "get") cfg --camelName --inBaseFile base.json -a get | jq .;;
          "put") cfg --camelName --inBaseFile base_local.json -a put --outBaseFile base.json;;
        esac
  qas:
    step:
      - qas -t ops/qas --parallel --reporter json > qas.json
      - qas --json-result qas.json --reporter html > qas.html
  helm:
    args:
      cmd:
        type: string
        default: diff
        validation: x in ["diff", "install", "upgrade", "delete"]
    step:
      - test "${K8S_CONTEXT}" == "$(kubectl config current-context)" || exit 1
      - sh ${DEP}/ops/tool/render.sh ${DEP}/ops/helm/rpc-app ${TMP}/helm/${NAME}
      - sh ${DEP}/ops/tool/render.sh ops/helm/values-adapter.yaml.tpl ${TMP}/helm/${NAME}/values-adapter.yaml
      - |
        case "${cmd}" in
          "diff"|"") helm diff upgrade "${NAME}" -n "${NAMESPACE}" "${TMP}/helm/${NAME}" -f "${TMP}/helm/${NAME}/values-adapter.yaml" --allow-unreleased;;
          "install") helm install "${NAME}" -n "${NAMESPACE}" "${TMP}/helm/${NAME}" -f "${TMP}/helm/${NAME}/values-adapter.yaml";;
          "upgrade") helm upgrade "${NAME}" -n "${NAMESPACE}" "${TMP}/helm/${NAME}" -f "${TMP}/helm/${NAME}/values-adapter.yaml";;
          "delete") helm delete "${NAME}" -n "${NAMESPACE}";;
        esac
